name: Auto Update Projects

on:
  schedule:
    # Runs daily at midnight UTC.
    # Adjust '0 0 * * *' if you need a different schedule.
    # Example: '0 12 * * *' for noon UTC
    # Example: '0 */6 * * *' for every 6 hours
    - cron: '0 0 * * *'
  
  # Allows manual triggering from the GitHub UI under the 'Actions' tab.
  workflow_dispatch:      

permissions:
  contents: write         # Required for committing and pushing changes (e.g., the log file)

jobs:
  update-projects:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v2 # Action to set up Python environment
      with:
        python-version: '3.9' # Specify the Python version

    - name: Install dependencies
      run: |
        # Install required Python packages. 'requests' is for API calls.
        pip install requests

    - name: Run the Python script
      # Environment variables passed to the Python script.
      # These retrieve values from GitHub Secrets or set optional parameters.
      env:
        KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }} # Your KoboToolbox API token (required)
        
        # Optional: Uncomment and set a value if you want to filter projects by title.
        # The script will only process projects whose title contains this substring (case-insensitive).
        # KOBO_PROJECT_FILTER_TITLE: "My Specific Project Name Part" 
        
        # Email Configuration (read from your GitHub Repository Secrets)
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}         # The email address to send from
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}     # The password for the sender email (use App Password for Gmail/Outlook)
        EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}   # Comma-separated list of recipient email addresses
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}           # Your SMTP server address (e.g., smtp.gmail.com)
        # SMTP_PORT: ${{ secrets.SMTP_PORT }}             # Your SMTP port (usually 587 for TLS, or 465 for SSL).
                                                          # If not set in secrets, script defaults to 587.
                                                          # Uncomment if you specifically want to set it via secrets.
      run: |
        python script.py # Execute your main Python script

    - name: Commit logs
      # Configure Git and commit the updated log file back to the repository.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub's auto-generated token for repository write access
      run: |
        git config --global user.name "github-actions"  # Set Git user for the commit
        git config --global user.email "actions@github.com" # Set Git email
        # Set remote URL with token for pushing changes securely
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add logs/project_update_log.txt # Stage the log file for commit
        # Commit changes. '|| echo "No changes to commit"' prevents failure if log file is unchanged.
        git commit -m "Update Kobo project log on $(date)" || echo "No changes to commit"
        git push # Push committed changes to the repository
